// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkvu847hILvoXvP0vN30wX2PW1vI1zYDE',
    appId: '1:859663979666:web:5860d47704d912eddc824b',
    messagingSenderId: '859663979666',
    projectId: 'goldapp-aba0c',
    authDomain: 'goldapp-aba0c.firebaseapp.com',
    storageBucket: 'goldapp-aba0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhxzgyMazpJBqyvlxFaqBm-b0S_Trgih4',
    appId: '1:859663979666:android:c3ca6a66b024bf24dc824b',
    messagingSenderId: '859663979666',
    projectId: 'goldapp-aba0c',
    storageBucket: 'goldapp-aba0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfkMfnnfwb3wcBXQU5XwUEsdYJcwsIBGU',
    appId: '1:859663979666:ios:a8b2463d9ef3dd6edc824b',
    messagingSenderId: '859663979666',
    projectId: 'goldapp-aba0c',
    storageBucket: 'goldapp-aba0c.appspot.com',
    iosBundleId: 'com.example.untitled6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfkMfnnfwb3wcBXQU5XwUEsdYJcwsIBGU',
    appId: '1:859663979666:ios:a05ae2f9a82d060cdc824b',
    messagingSenderId: '859663979666',
    projectId: 'goldapp-aba0c',
    storageBucket: 'goldapp-aba0c.appspot.com',
    iosBundleId: 'com.example.untitled6.RunnerTests',
  );
}
